org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
android.compileSdk=34
android.targetSdk=34
android.minSdk=23
android.lintOptions.checkReleaseBuilds=false