services:

  db:
    image: postgres:15-alpine
    container_name: ${DB_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  osrm:
    image: osrm/osrm-backend:latest
    container_name: pulse-osrm
    command: >
      osrm-routed
      --algorithm mld
      /data/bangalore-latest.osrm
    volumes:
      - ./osrm-data:/data
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres_data:
