services:

  db:
    image: postgres:15-alpine
    container_name: ${DB_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  osrm:
    image: osrm/osrm-backend:latest
    container_name: ${OSRM_NAME}
    command: >
      osrm-routed
      --algorithm mld
      /data/bangalore-latest.osrm
    volumes:
      - ./osrm-data:/data
    ports:
      - "${OSRM_PORT}:${OSRM_PORT}"
    restart: always

  neo4j:
    image: neo4j:5.12
    container_name: pulse_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulse_server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - NEO4J_URI=bolt://neo4j:7687
      - OSRM_BASE_URL=http://osrm:5000
    depends_on:
      - db
      - neo4j
      - osrm

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
